### ISSUE TITLE
When checking details of a device the custom label names aren't set

### ISSUE THREAD

**Issue by robertraaijmakers** [swttt/HomeyDash#4]
**What OS and browser are you using?**
Android Chrome

**What did you try to achieve?**
I was just clicking through the devices and checked my current energy usage.

**What was the result?**
I saw the same label names.

**What did you expect as result?**
The custom label names set by the device.

**Any other remarks**
App looks great!

![screenshot_20171029-085256](https://user-images.githubusercontent.com/1773099/32141713-314eec66-bc87-11e7-9a94-5c34666f64c0.png)

**Comment by robertraaijmakers** [comment]
That is a whole lot of information :)

{
  "status": 200,
  "result": {
    "id": "1da0cdd7-5533-435e-9b4f-5b47810441ad",
    "name": "Slimme Meter",
    "driver": {
      "uri": "homey:app:com.iungo",
      "id": "energy_meter",
      "path": "\/opt\/user\/apps\/7217a049577f5afa662363f483a40c22\/drivers\/energy_meter",
      "assetsPath": "\/app\/com.iungo\/drivers\/energy_meter\/assets\/",
      "wwwPath": "\/app\/com.iungo\/",
      "owner_name": "Iungo",
      "owner_icon": "\/app\/com.iungo\/assets\/icon.svg",
      "virtual": false,
      "metadata": {
        "name": {
          "en": "Energy Controller",
          "nl": "Energie Controller"
        },
        "class": "sensor",
        "capabilities": [
          "measure_power",
          "meter_power.sum",
          "meter_gas",
          "meter_gas.sum",
          "meter_power.t1",
          "meter_power.t2",
          "meter_power.rt1",
          "meter_power.rt2",
          "measure_power.import",
          "measure_power.export",
          "measure_current.l1",
          "measure_current.l2",
          "measure_current.l3",
          "measure_power.l1i",
          "measure_power.l2i",
          "measure_power.l3i",
          "measure_power.l1e",
          "measure_power.l2e",
          "measure_power.l3e"
        ],
        "capabilitiesOptions": {
          "measure_power": {
            "title": {
              "en": "Power",
              "nl": "Verbruik"
            }
          },
          "meter_power.sum": {
            "title": {
              "en": "Power Total",
              "nl": "Totaal verbruik"
            }
          },
          "meter_power.t1": {
            "title": {
              "en": "Power T1",
              "nl": "Telwerk 1"
            }
          },
          "meter_power.t2": {
            "title": {
              "en": "Power T2",
              "nl": "Telwerk 2"
            }
          },
          "meter_power.rt1": {
            "title": {
              "en": "Power -T1",
              "nl": "Teruglevering 1"
            }
          },
          "meter_power.rt2": {
            "title": {
              "en": "Power -T2",
              "nl": "Teruglevering 2"
            }
          },
          "meter_gas": {
            "title": {
              "en": "Gas",
              "nl": "Gas"
            }
          },
          "meter_gas.sum": {
            "title": {
              "en": "Power Total",
              "nl": "Totaal verbruik"
            }
          },
          "measure_current.l1": {
            "title": {
              "en": "Current L1",
              "nl": "Stroomsterkte L1"
            }
          },
          "measure_current.l2": {
            "title": {
              "en": "Current L2",
              "nl": "Stroomsterkte L2"
            }
          },
          "measure_current.l3": {
            "title": {
              "en": "Current L2",
              "nl": "Stroomsterkte L3"
            }
          },
          "measure_power.import": {
            "title": {
              "en": "Power Import",
              "nl": "Vermogen Import"
            }
          },
          "measure_power.export": {
            "title": {
              "en": "Power Export",
              "nl": "Vermogen Export"
            }
          },
          "measure_power.l1i": {
            "title": {
              "en": "Import 1",
              "nl": "Import 1"
            }
          },
          "measure_power.l2i": {
            "title": {
              "en": "Import 2",
              "nl": "Import 2"
            }
          },
          "measure_power.l3i": {
            "title": {
              "en": "Import 3",
              "nl": "Import 3"
            }
          },
          "measure_power.l1e": {
            "title": {
              "en": "Export 1",
              "nl": "Export 1"
            }
          },
          "measure_power.l2e": {
            "title": {
              "en": "Export 2",
              "nl": "Export 2"
            }
          },
          "measure_power.l3e": {
            "title": {
              "en": "Export 3",
              "nl": "Export 3"
            }
          }
        },
        "icon": "\/app\/com.iungo\/drivers\/energy_meter\/assets\/icon.svg",
        "settings": [
          {
            "type": "group",
            "label": {
              "en": "Tariff settings",
              "nl": "Tarief instellingen"
            },
            "children": [
              {
                "id": "Cost-T1",
                "type": "number",
                "label": {
                  "en": "T1",
                  "nl": "Telwerk 1"
                },
                "value": 0,
                "attr": {
                  "min": 0,
                  "max": 5,
                  "step": 1.0e-5
                }
              },
              {
                "id": "Cost-T2",
                "type": "number",
                "label": {
                  "en": "T2",
                  "nl": "Telwerk 2"
                },
                "value": 0,
                "attr": {
                  "min": 0,
                  "max": 5,
                  "step": 1.0e-5
                }
              },
              {
                "id": "Cost-nT1",
                "type": "number",
                "label": {
                  "en": "Redelivery T1",
                  "nl": "Teruglevering 1"
                },
                "value": 0,
                "attr": {
                  "min": 0,
                  "max": 5,
                  "step": 1.0e-5
                }
              },
              {
                "id": "Cost-nT2",
                "type": "number",
                "label": {
                  "en": "Redelivery T2",
                  "nl": "Teruglevering 2"
                },
                "value": 0,
                "attr": {
                  "min": 0,
                  "max": 5,
                  "step": 1.0e-5
                }
              },
              {
                "id": "Cost-gas",
                "type": "number",
                "label": {
                  "en": "Gas",
                  "nl": "Gas"
                },
                "value": 0,
                "attr": {
                  "min": 0,
                  "max": 5,
                  "step": 1.0e-5
                }
              }
            ]
          },
          {
            "type": "group",
            "label": {
              "en": "Gas meter settings",
              "nl": "Instellingen gasmeter"
            },
            "children": [
              {
                "id": "Gas-interval",
                "type": "number",
                "label": {
                  "en": "Gas interval",
                  "nl": "Gas interval"
                },
                "value": 3600,
                "attr": {
                  "min": 1,
                  "max": 86400,
                  "step": 60
                }
              }
            ]
          }
        ],
        "pair": true,
        "unpair": false,
        "repair": false
      },
      "ready": true
    },
    "zone": {
      "id": "855113f1-f488-4223-b675-2f01270f573e",
      "name": "Ground floor",
      "icon": "default",
      "index": 1,
      "parent": "9919ee1e-ffbc-480b-bc4b-77fb047e9e68"
    },
    "data": {
      "id": "538d72d9",
      "iungo_id": "abc-123"
    },
    "icon": "\/app\/com.iungo\/drivers\/energy_meter\/assets\/icon.svg",
    "settings": {
      "Cost-T1": 0.357,
      "Cost-T2": 0.3812,
      "Cost-nT1": 0.3,
      "Cost-nT2": 0.38,
      "Cost-gas": 1.1885,
      "Gas-interval": 3600
    },
    "class": "sensor",
    "capabilities": {
      "measure_power": {
        "uri": "homey:manager:devices",
        "id": "measure_power",
        "type": "number",
        "title": {
          "en": "Power",
          "nl": "Energie"
        },
        "units": {
          "en": "W"
        },
        "desc": {
          "en": "Power in Watt (W)",
          "nl": "Energie in Watt (W)"
        },
        "chartType": "stepLine",
        "decimals": 2,
        "getable": true,
        "setable": false
      },
      "meter_power.t1": {
        "uri": "homey:manager:devices",
        "id": "meter_power",
        "type": "number",
        "title": {
          "en": "Power Meter",
          "nl": "Stroommeter"
        },
        "decimals": 2,
        "units": {
          "en": "KWh"
        },
        "chartType": "spline",
        "desc": {
          "en": "Power usage in KiloWattHour (kWh)",
          "nl": "Stroomverbuik in KiloWattUur (kWh)"
        },
        "getable": true,
        "setable": false
      },
      "meter_power.t2": {
        "uri": "homey:manager:devices",
        "id": "meter_power",
        "type": "number",
        "title": {
          "en": "Power Meter",
          "nl": "Stroommeter"
        },
        "decimals": 2,
        "units": {
          "en": "KWh"
        },
        "chartType": "spline",
        "desc": {
          "en": "Power usage in KiloWattHour (kWh)",
          "nl": "Stroomverbuik in KiloWattUur (kWh)"
        },
        "getable": true,
        "setable": false
      },
      "meter_gas": {
        "uri": "homey:manager:devices",
        "id": "meter_gas",
        "type": "number",
        "title": {
          "en": "Gas Meter",
          "nl": "Gasmeter"
        },
        "min": 0,
        "decimals": 2,
        "chartType": "spline",
        "units": {
          "en": "m\u00b3"
        },
        "desc": {
          "en": "Gas usage in Cubic Meter (m\u00b3)",
          "nl": "Gas gebruik in Kubieke Meter (m\u00b3)"
        },
        "getable": true,
        "setable": false
      },
      "meter_power.rt1": {
        "uri": "homey:manager:devices",
        "id": "meter_power",
        "type": "number",
        "title": {
          "en": "Power Meter",
          "nl": "Stroommeter"
        },
        "decimals": 2,
        "units": {
          "en": "KWh"
        },
        "chartType": "spline",
        "desc": {
          "en": "Power usage in KiloWattHour (kWh)",
          "nl": "Stroomverbuik in KiloWattUur (kWh)"
        },
        "getable": true,
        "setable": false
      },
      "meter_power.rt2": {
        "uri": "homey:manager:devices",
        "id": "meter_power",
        "type": "number",
        "title": {
          "en": "Power Meter",
          "nl": "Stroommeter"
        },
        "decimals": 2,
        "units": {
          "en": "KWh"
        },
        "chartType": "spline",
        "desc": {
          "en": "Power usage in KiloWattHour (kWh)",
          "nl": "Stroomverbuik in KiloWattUur (kWh)"
        },
        "getable": true,
        "setable": false
      }
    },
    "capabilitiesArray": [
      "measure_power",
      "meter_power.t1",
      "meter_power.t2",
      "meter_gas",
      "meter_power.rt1",
      "meter_power.rt2"
    ],
    "capabilitiesOptions": {
      "measure_power": {
        "title": {
          "en": "Power",
          "nl": "Verbruik"
        }
      },
      "meter_power.t1": {
        "title": {
          "en": "Power T1",
          "nl": "Telwerk 1"
        }
      },
      "meter_power.t2": {
        "title": {
          "en": "Power T2",
          "nl": "Telwerk 2"
        }
      },
      "meter_gas": {
        "title": {
          "en": "Gas",
          "nl": "Gas"
        }
      },
      "meter_power.rt1": {
        "title": {
          "en": "Power -T1",
          "nl": "Teruglevering 1"
        }
      },
      "meter_power.rt2": {
        "title": {
          "en": "Power -T2",
          "nl": "Teruglevering 2"
        }
      }
    },
    "flags": [
      
    ],
    "mobile": {
      "components": [
        {
          "id": "icon",
          "capabilities": [
            
          ]
        },
        {
          "id": "sensor",
          "capabilities": [
            "measure_power",
            "meter_power.t1",
            "meter_power.t2",
            "meter_gas",
            "meter_power.rt1",
            "meter_power.rt2"
          ]
        }
      ]
    },
    "order": 13,
    "online": true,
    "state": {
      "measure_power": 348,
      "meter_power.t1": 4231.2,
      "meter_power.t2": 3981.59,
      "meter_gas": 1027.03,
      "meter_power.rt1": 0,
      "meter_power.rt2": 0
    },
    "lastUpdated": {
      "measure_power": "2017-10-29T09:57:18.926Z",
      "meter_power.t1": "2017-10-29T09:56:58.924Z",
      "meter_power.t2": "2017-10-27T21:00:04.171Z",
      "meter_gas": "2017-10-29T08:02:09.180Z",
      "meter_power.rt1": "2017-10-20T15:54:48.723Z",
      "meter_power.rt2": "2017-10-20T15:54:48.723Z"
    },
    "available": true
  }
}

**Comment by swttt** [comment]
Can't test this, since i don't own a device with such capabilities.
BUT it should be fixed now... Could you confirm this?

**Comment by robertraaijmakers** [comment]
Sorry, still doesn't work, do I have to reset or clear some cache or something? Did reload the page.

**Comment by swttt** [comment]
Should really be fixed now 😁

**Comment by robertraaijmakers** [comment]
Yes, works!
