### ISSUE TITLE
Widgets are placed over each other after reloading page

### ISSUE THREAD

**Issue by jantje88** [swttt/HomeyDash#57]
**What OS and browser are you using?**

Default Android browser on [Android 6.0.1](https://forum.xda-developers.com/eee-pad-transformer/development/rom-t3318496) on a ASUS Transformer TF101 tablet.

**What did you try to achieve?**

Remove local storage and add one or more widgets and move them to a place on the dashboard. Switch to device tab or reload the page.

**What was the result?**

All widgets are place over each other.

**What did you expect as result?**

Widgets keeps on the same place where I moved them to on the dashboard.

**Any other remarks**

...

**Comment by swttt** [comment]
Just to check, do you use the beta or the stable version?

**Comment by jantje88** [comment]
Happens with both stable as beta.

**Comment by swttt** [comment]
I pushed an update with a fixed widgets container to the beta branch. Could you test on the beta if this solves the problem?

**Comment by JBS5** [comment]
Unfortunately the issue isn't fixed for me. Not on beta (and not in the stable).
